FS = 500.0

WIN_SEC = 1.0
HOP_SEC = 0.1

WIN_SAMPLES = int(FS * WIN_SEC)    # 500
HOP_SAMPLES = int(FS * HOP_SEC)    # 50

CONFIRM_N = 3
HOLD_SEC = 0.8
HOLD_HOPS = int(HOLD_SEC / HOP_SEC)  # 8

SCOPE_SEC = 5.0
SCOPE_SAMPLES = int(FS * SCOPE_SEC)

N_CH = 8
N_CLASSES = 10
MARKER_LABEL = 100
